version: '3.8'

services:
  keycloak:
    container_name: keycloak-fatm
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 9092:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    command:
      - "start-dev"
networks:
  spring-demo:
    driver: bridge